<?php 
$marca = 'sepco';
$thisPage = 'productos';
$thisCategory = 'empaquetaduras';
$titlePage = " Empaquetaduras Industriales</br>";
$description ="Fabricamos  Empaquetaduras Industriales</br> de alto rendimiento.";
$keywords ="empaques, empaquetadura, industrial, selllos, sellado,fabrica";
?>

<?php include 'header.php';?>
<?php include 'menu.php';?>

<!-- Inicia contenido de la página
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->
<div class="row">
    <div class="container">
        <!-- Inicia Sidebar de Productos -->
        <?php include 'sidebar-products.php'; ?>
        <!-- Termina Sidebar de Productos -->
       

        <!-- Inicia caja de marcas -->
        <?php include 'marca-head.php'; ?>
        <!-- Termina caja de marcas -->

        <div class="col-md-9">

			<div id="page-content" class="row border-bottom pb50 products-image" >
        		
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/01-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales 2"><img src="productos/200x200/01-sepco/02-empaquetaduras/01-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>2</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/02-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales 180"><img src="productos/200x200/01-sepco/02-empaquetaduras/02-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>180</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/03-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales 219"><img src="productos/200x200/01-sepco/02-empaquetaduras/03-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>219</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/04-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales 310"><img src="productos/200x200/01-sepco/02-empaquetaduras/04-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>310</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/05-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales 2210 Spool"><img src="productos/200x200/01-sepco/02-empaquetaduras/05-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>2210 Spool</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/06-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DS6225"><img src="productos/200x200/01-sepco/02-empaquetaduras/06-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>DS6225</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/07-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8481"><img src="productos/200x200/01-sepco/02-empaquetaduras/07-empaquetaduras.jpg"><p> Empaquetaduras Anillos</br>DSCF8481</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/08-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8482"><img src="productos/200x200/01-sepco/02-empaquetaduras/08-empaquetaduras.jpg"><p> Empaquetaduras Anillos</br>DSCF8482</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/09-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8485"><img src="productos/200x200/01-sepco/02-empaquetaduras/09-empaquetaduras.jpg"><p> Empaquetaduras Anillos</br>DSCF8485</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/10-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8511"><img src="productos/200x200/01-sepco/02-empaquetaduras/10-empaquetaduras.jpg"><p> Empaquetaduras Anillos</br>DSCF8511</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/11-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8514"><img src="productos/200x200/01-sepco/02-empaquetaduras/11-empaquetaduras.jpg"><p> Empaquetaduras Anillos</br>DSCF8514</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/12-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8521"><img src="productos/200x200/01-sepco/02-empaquetaduras/12-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>DSCF8521</p></a></div>

                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/13-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8523"><img src="productos/200x200/01-sepco/02-empaquetaduras/13-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>GFO8523</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/14-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8541"><img src="productos/200x200/01-sepco/02-empaquetaduras/14-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>GFO8541</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/15-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8547"><img src="productos/200x200/01-sepco/02-empaquetaduras/15-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>DSCF8547</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/16-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8550"><img src="productos/200x200/01-sepco/02-empaquetaduras/16-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>DSCF8550</p></a></div>
                
                <!-- <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/17-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8561"><img src="productos/200x200/01-sepco/02-empaquetaduras/17-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>DSCF8561</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/18-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8574"><img src="productos/200x200/01-sepco/02-empaquetaduras/18-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>DSCF8574</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/19-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales DSCF8575"><img src="productos/200x200/01-sepco/02-empaquetaduras/19-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>DSCF8575</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/20-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales G2"><img src="productos/200x200/01-sepco/02-empaquetaduras/20-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>G2</p></a></div>
                 -->
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/21-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales Graphaseal II"><img src="productos/200x200/01-sepco/02-empaquetaduras/21-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>Graphaseal II</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/22-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales"><img src="productos/200x200/01-sepco/02-empaquetaduras/22-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br></p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/23-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales Hollowcore"><img src="productos/200x200/01-sepco/02-empaquetaduras/23-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>Hollowcore</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/24-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML402"><img src="productos/200x200/01-sepco/02-empaquetaduras/24-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML402</p></a></div>
                
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/25-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML560   "><img src="productos/200x200/01-sepco/02-empaquetaduras/25-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML560</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/26-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML911W  "><img src="productos/200x200/01-sepco/02-empaquetaduras/26-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML911W</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/27-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2001  "><img src="productos/200x200/01-sepco/02-empaquetaduras/27-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2001</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/28-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2001CC"><img src="productos/200x200/01-sepco/02-empaquetaduras/28-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2001CC</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/29-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2003  "><img src="productos/200x200/01-sepco/02-empaquetaduras/29-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2003</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/30-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2225A "><img src="productos/200x200/01-sepco/02-empaquetaduras/30-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2225A </p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/31-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2235  "><img src="productos/200x200/01-sepco/02-empaquetaduras/31-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2235</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/33-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2236  "><img src="productos/200x200/01-sepco/02-empaquetaduras/33-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2236</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/34-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2238  "><img src="productos/200x200/01-sepco/02-empaquetaduras/34-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2238</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/35-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2240  "><img src="productos/200x200/01-sepco/02-empaquetaduras/35-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2240</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/36-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2250  "><img src="productos/200x200/01-sepco/02-empaquetaduras/36-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2250</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/37-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2254  "><img src="productos/200x200/01-sepco/02-empaquetaduras/37-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2254</p></a></div>
                
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/38-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML2400"><img src="productos/200x200/01-sepco/02-empaquetaduras/38-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML2400</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/39-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML4002"><img src="productos/200x200/01-sepco/02-empaquetaduras/39-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML4002</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/41-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML4002M"><img src="productos/200x200/01-sepco/02-empaquetaduras/41-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML4002M</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/42-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML4004"><img src="productos/200x200/01-sepco/02-empaquetaduras/42-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML4004</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/43-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML4444"><img src="productos/200x200/01-sepco/02-empaquetaduras/43-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML4444</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/44-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML4460"><img src="productos/200x200/01-sepco/02-empaquetaduras/44-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML4460</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/45-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML4461"><img src="productos/200x200/01-sepco/02-empaquetaduras/45-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML4461</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/46-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML4500"><img src="productos/200x200/01-sepco/02-empaquetaduras/46-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML4500</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/47-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML4800"><img src="productos/200x200/01-sepco/02-empaquetaduras/47-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML4800</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/48-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML6225A"><img src="productos/200x200/01-sepco/02-empaquetaduras/48-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML6225A</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/49-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML6402"><img src="productos/200x200/01-sepco/02-empaquetaduras/49-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML6402</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/50-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML8002"><img src="productos/200x200/01-sepco/02-empaquetaduras/50-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML8002</p></a></div>
                
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/51-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales ML8004 "><img src="productos/200x200/01-sepco/02-empaquetaduras/51-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>ML8004 </p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/56-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales Packing Pusher"><img src="productos/200x200/01-sepco/02-empaquetaduras/56-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>Packing Pusher</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/57-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales paklube"><img src="productos/200x200/01-sepco/02-empaquetaduras/57-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>Paklube</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/58-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales Rings"><img src="productos/200x200/01-sepco/02-empaquetaduras/58-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>Rings</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/59-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales RV2225"><img src="productos/200x200/01-sepco/02-empaquetaduras/59-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>RV2225</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/60-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales SEAT-IT Bucket"><img src="productos/200x200/01-sepco/02-empaquetaduras/60-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>SEAT-IT Bucket</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/61-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales Spiral Pak"><img src="productos/200x200/01-sepco/02-empaquetaduras/61-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>Spiral Pak</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/62-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales SS638"><img src="productos/200x200/01-sepco/02-empaquetaduras/62-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>SS638</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/52-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales "><img src="productos/200x200/01-sepco/02-empaquetaduras/52-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br></p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/53-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales "><img src="productos/200x200/01-sepco/02-empaquetaduras/53-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br></p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/54-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales "><img src="productos/200x200/01-sepco/02-empaquetaduras/54-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br></p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/55-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales "><img src="productos/200x200/01-sepco/02-empaquetaduras/55-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br></p></a></div>
                
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/63-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales TBSS-01"><img src="productos/200x200/01-sepco/02-empaquetaduras/63-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>TBSS-01</p></a></div>
                <div class="col-md-3"><a href="productos/bigs/01-sepco/02-empaquetaduras/64-empaquetaduras.jpg" data-lightbox="image-1" data-title="Empaquetaduras Industriales Washer Pak"><img src="productos/200x200/01-sepco/02-empaquetaduras/64-empaquetaduras.jpg"><p> Empaquetaduras Industriales</br>Washer Pak</p></a></div>
            </div>
			
        </div>
    </div>
</div>
<?php include 'footer.php' ?>