<?php 
$marca = 'sepco';
$thisPage = 'productos';
$thisCategory = 'sellos-mecanicos';
$titlePage = "Sellos Mecánicos";
$description ="Venta y reparación de Sellos Mecánicos.";
$keywords ="sellos mecánicos, industriales";
?>

<?php include 'header.php';?>
<?php include 'menu.php';?>

<!-- Inicia contenido de la página
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->
<div class="row">
    <div class="container">
        <!-- Inicia Sidebar de Productos -->
        <?php include 'sidebar-products.php'; ?>
        <!-- Termina Sidebar de Productos -->
       

        <!-- Inicia caja de marcas -->
        <?php include 'marca-head.php'; ?>
        <!-- Termina caja de marcas -->

        <div class="col-sm-8">

			<div id="page-content" class="row border-bottom pb50 products-image" >
        		
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/02-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos BSS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/02-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>BSS</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/03-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos CGS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/03-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>CGS</p></a></div>
                <!-- <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/04-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos CGS Grease Kit"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/04-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>CGS Grease Kit</p></a></div> -->
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/05-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos CGS Grease Kit 02"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/05-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br> CGS Grease Kit 02</p></a></div>                 <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/06-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos CMD"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/06-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>CMD</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/07-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos CSO"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/07-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>CSO</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/08-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos DRC"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/08-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>DRC</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/09-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos DSCF8454"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/09-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>DSCF8454</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/10-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos DSCF8455"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/10-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>DSCF8455</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/11-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos DSCF8457"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/11-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>DSCF8457</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/12-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos DSCF8467"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/12-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>DSCF8467</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/13-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos DSCF8471"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/13-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>DSCF8471</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/14-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos DTP"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/14-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>DTP</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/15-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos EDP"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/15-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>EDP</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/16-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos ESC"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/16-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>ESC</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/17-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos ESD"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/17-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>ESD</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/18-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos G5FT1846"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/18-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>G5FT1846</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/19-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos G5FT1848"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/19-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>G5FT1848</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/20-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos G5FT1850"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/20-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>G5FT1850</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/21-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos GEM"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/21-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>GEM</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/22-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos HDN"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/22-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>HDN</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/23-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos HOS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/23-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>HOS</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/24-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos KMS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/24-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>KMS</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/26-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos NM2"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/26-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>NM2</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/27-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos NMC"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/27-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>NMC</p></a></div>

                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/29-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos OMS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/29-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>OMS</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/31-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos OSS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/31-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>OSS</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/32-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos OUS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/32-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>OUS</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/34-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos PDC"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/34-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>PDC</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/35-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos PDS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/35-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>PDS</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/36-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos PRO"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/36-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>PRO</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/37-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos RBD"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/37-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>RBD</p></a></div>
                <!-- <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/38-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos Rediload"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/38-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>Rediload</p></a></div> -->
                
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/43-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos SMD"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/43-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>SMD</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/44-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos SRC 02"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/44-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>SRC 02</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/45-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos SRC"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/45-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>SRC</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/46-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos SRS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/46-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>SRS</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/48-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos SSF w Back press valve"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/48-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>SSF w Back press valve</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/51-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos TJS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/51-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>TJS</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/52-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos VGS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/52-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>VGS</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/53-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos VSR"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/53-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>VSR</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/54-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos XRS"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/54-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>XRS</p></a></div>
                

                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/47-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos SSF"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/47-sellos-mecanicos.jpg"><p>Flow Meter</br>SSF</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/41-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos SDF"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/41-sellos-mecanicos.jpg"><p>Flow Meter</br>SDF</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/39-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos RF mount"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/39-sellos-mecanicos.jpg"><p>Asiento Estacionario</br>RF mount</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/42-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos Single spring Group"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/42-sellos-mecanicos.jpg"><p>Sellos Mecánicos</br>Sello de Volumen</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/49-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos stdT"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/49-sellos-mecanicos.jpg"><p>Asiento Estacionario</br>STDT</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/25-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos Lshape"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/25-sellos-mecanicos.jpg"><p>Asiento Estacionario</br>LSHAPE </p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/28-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos oemT"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/28-sellos-mecanicos.jpg"><p>Asiento Estacionario</br>OEMT</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/30-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos Oring Mount"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/30-sellos-mecanicos.jpg"><p>Asiento Estacionario</br>Oring Mount</p></a></div>
                <div class="col-md-3 col-xs-6 col-sm-4"><a href="productos/bigs/01-sepco/01-sellos-mecanicos/01-sellos-mecanicos.jpg" data-lightbox="image-1" data-title="Sellos Mecánicos A2AWMS-3D"><img class="img-responsive" src="productos/200x200/01-sepco/01-sellos-mecanicos/01-sellos-mecanicos.jpg"><p>Tanque</br>A2AWMS-3D</p></a></div>

        	</div>
			
        </div>
    </div>
</div>
<?php include 'footer.php' ?>